heat_template_version: pike

description: >
  Creates a port on the InternalApi network, using a map of IPs per role.
  Each role has a map of IPs in <Role>IPs parameters, with a list of IPs by
  network (lower_name or lower case). For example:
  ControllerIPs:
    external:
    - 1.2.3.4 # First controller
    - 1.2.3.5 # Second controller

parameters:
  InternalApiNetName:
    description: The name of the internal_api network.
    default: internal_api
    type: string
  PortName:
    description: Name of the port
    default: ''
    type: string
  ControlPlaneIP: # Here for compatibility with noop.yaml
    description: IP address on the control plane
    default: ''
    type: string
  ControlPlaneNetwork: # Here for compatibility with ctlplane_vip.yaml
    description: The name of the undercloud Neutron control plane
    default: ctlplane
    type: string
  IPPool: # Set in <Role>IPs map, see environments/ips-from-pool-all.yaml
    default: {}
    type: json
  NodeIndex: # First node in the role will get first IP, and so on...
    default: 0
    type: number
  InternalApiNetCidr:
    default: 172.16.2.0/24
    description: Cidr for the internal_api network.
    type: string

outputs:
  ip_address:
    description: InternalApi network IP
    value: {get_param: [IPPool, {get_param: InternalApiNetName}, {get_param: NodeIndex}]}
  ip_address_uri:
    description: InternalApi network IP (for compatibility with internal_api_v6.yaml)
    value: {get_param: [IPPool, {get_param: InternalApiNetName}, {get_param: NodeIndex}]}
  ip_subnet:
    description: IP/Subnet CIDR for the InternalApi network IP
    value:
      list_join:
      - ''
      - - {get_param: [IPPool, {get_param: InternalApiNetName}, {get_param: NodeIndex}]}
        - '/'
        - {str_split: ['/', {get_param: InternalApiNetCidr}, 1]}
